name: Build Remote Gemini Project

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout remote repository
        uses: actions/checkout@v4
        with:
          repository: tgjones/gemini
          ref: master
          path: gemini-src
          fetch-depth: 0 # 修复版本计算报错

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet packages
        run: nuget restore gemini-src/src/Gemini.sln

      - name: Build solution
        run: |
          msbuild gemini-src/src/Gemini.sln `
            /p:Configuration=Release `
            /p:Platform="Any CPU"

      - name: Upload Demo EXE
        uses: actions/upload-artifact@v4
        with:
          name: Gemini-Demo-Binary
          path: |
            gemini-src/src/Gemini.Demo/bin/Release/**
            !gemini-src/src/Gemini.Demo/bin/Release/**/*.pdb
